package report

// SlotSource describes how a slot's image is produced.
type SlotSource int

const (
	// SourceManual: the image is uploaded by the operator.
	SourceManual SlotSource = iota
	// SourceAutoChart: the image is generated by the engine from metrics.
	SourceAutoChart
)

// Slot is a fixed image placeholder in the template. The catalog is the single
// documentary source of truth: for each figure it states its title, what
// evidence it represents, its function/section in the narrative, and how it is
// produced. The engine never infers or classifies images; the template author
// places each slot via the drawing's Alt-Text (= the slot Key). Figures are
// never added, removed or renumbered.
type Slot struct {
	Key      string     `json:"key"`
	Title    string     `json:"title"`
	Evidence string     `json:"evidence"`
	Section  string     `json:"section"`
	Source   SlotSource `json:"-"`
	Required bool       `json:"required"`
}

// SourceName returns "manual" or "auto" for serialization/UI.
func (s Slot) SourceName() string {
	if s.Source == SourceAutoChart {
		return "auto"
	}
	return "manual"
}

// Slots is the immutable catalog of image placeholders, in document order.
// Note the intentional 8 -> 10 gap (no "Figura 9"). Only grafico_1 is generated.
var Slots = []Slot{
	{"logo", "Logo del cliente", "Logotipo de la empresa cliente (portada)", "Portada", SourceManual, true},
	{"figura_1", "Figura 1: Correos identificados", "Captura de los correos de phishing identificados", "Sección 3 – Ejecución de la campaña", SourceManual, true},
	{"figura_2", "Figura 2: Plantilla suplantada", "Captura de la plantilla de correo suplantada", "Sección 3 – Ejecución de la campaña", SourceManual, true},
	{"figura_3", "Figura 3: Identificación del correo falso", "Captura señalando el remitente/dominio falso", "Sección 4 – Puntos clave", SourceManual, true},
	{"figura_4", "Figura 4: Hipervínculo de redirección", "Captura del hipervínculo malicioso", "Sección 4 – Puntos clave", SourceManual, true},
	{"figura_5", "Figura 5: Login de captura de credenciales", "Captura de la landing de captura de credenciales", "Sección 4 – Puntos clave", SourceManual, true},
	{"figura_6", "Figura 6: Redirección a reunión cancelada", "Captura de la reunión/Teams cancelada", "Sección 4 – Puntos clave", SourceManual, true},
	{"grafico_1", "Gráfico 1: Resultados", "Gráfica de resultados (generada automáticamente)", "Sección 5 – Resultados", SourceAutoChart, true},
	{"evidencia_flujo", "Evidencia de credenciales válidas (flujo)", "Captura del flujo de autenticación con credenciales válidas", "Sección 6 – Evidencia de credenciales válidas", SourceManual, true},
	{"figura_7", "Figura 7: Evidencia de Credenciales Usuario 1", "Captura de credenciales válidas del usuario", "Sección 7 – Evidencias de credenciales válidas", SourceManual, true},
	{"figura_8", "Figura 8: Evidencia de Acceso por falta de 2FA", "Captura del acceso/2FA", "Sección 7 – Evidencias de credenciales válidas", SourceManual, true},
	{"figura_10", "Figura 10: Usuarios que enviaron datos", "Captura del anexo de usuarios que enviaron datos", "Sección 10 – Anexos", SourceManual, true},
}

// slotByKey indexes the catalog for O(1) lookups.
var slotByKey = func() map[string]Slot {
	m := make(map[string]Slot, len(Slots))
	for _, s := range Slots {
		m[s.Key] = s
	}
	return m
}()

// IsSlot reports whether key is a known image slot.
func IsSlot(key string) bool {
	_, ok := slotByKey[key]
	return ok
}

// RequiredSlots returns the keys of all slots that must be present in a template.
func RequiredSlots() []string {
	out := make([]string, 0, len(Slots))
	for _, s := range Slots {
		if s.Required {
			out = append(out, s.Key)
		}
	}
	return out
}
